import ModulesWrapper from '../../ModulesRegister';
import Help from '../../Help';
import About from '../../About';
import SingleCommandModule from '../../SingleCommandModule';
import Sticker from '../../Sticker';
import YouTube from '../../YouTube';
import Horoscopo from '../../Horoscopo';
import Google from '../../Google';
import Transcribe from '../../Transcribe';
import LyricsFinder from '../../Lyrics';
import CopypastaManager from '../../Copypasta';
import Logger from '../../Logger';
import Weather from '../../Weather';
import Meme from '../../MemeMaker';
import TextTransform from '../../TextTransform';
import Finance from '../../Finance';
import Wordle from '../../Wordle';
import Raffle from '../../Raffle';
import Translate from 'src/Modules/Translate';
import Ping from '../../Ping';
import Dictionary from '../../Dictionary';
import OpenAI from 'src/Modules/OpenAi';
import PatchNotes from 'src/Modules/PatchNotes';

import { kudurolify } from '../../TextTransform/Transformations';
import MensagensModule from 'src/Modules/BomDia';
import Admin from 'src/Modules/Admin';
import Offend from 'src/Modules/Offend';
import Bored from 'src/Modules/Bored';
import Reset from 'src/Modules/Reset';
import Ban from 'src/Modules/Ban';
import Reveal from 'src/Modules/Reveal';
import Delete from 'src/Modules/Delete';

const modulesWrapper = new ModulesWrapper();
const help = new Help();
const sticker = new Sticker();
const horoscope = new Horoscopo();
const google = new Google();
const replySpeak = new SingleCommandModule(google.replySpeak, google);
const raffle = new Raffle();
const dictionary = new Dictionary();
const youtube = new YouTube();

modulesWrapper.registerModule('help', help);
modulesWrapper.registerModule('menu', help);
modulesWrapper.registerModule('about', new About());

modulesWrapper.registerModule('sticker', sticker);
modulesWrapper.registerModule('s', sticker);
modulesWrapper.registerModule('yt', youtube);
modulesWrapper.registerModule('youtube', youtube);
modulesWrapper.registerModule('horoscopo', horoscope);
modulesWrapper.registerModule('horóscopo', horoscope);
modulesWrapper.registerModule('google', google);
modulesWrapper.registerModule('speak', replySpeak);
modulesWrapper.registerModule('transcribe', new Transcribe());
modulesWrapper.registerModule('lyrics', new LyricsFinder());
modulesWrapper.registerModule('copypasta', new CopypastaManager());
modulesWrapper.registerModule('log', new Logger());
modulesWrapper.registerModule('weather', new Weather());
modulesWrapper.registerModule('meme', new Meme());
modulesWrapper.registerModule('kuduro', new TextTransform(kudurolify));
modulesWrapper.registerModule('finance', new Finance());
modulesWrapper.registerModule('wordle', new Wordle());
modulesWrapper.registerModule('sorteio', raffle);
modulesWrapper.registerModule('raffle', raffle);
modulesWrapper.registerModule('translate', new Translate());
modulesWrapper.registerModule('ping', new Ping());
modulesWrapper.registerModule('dicionario', dictionary);
modulesWrapper.registerModule('significado', dictionary);
modulesWrapper.registerModule('openai', new OpenAI());
// modulesWrapper.registerModule("download", new Downloader());
modulesWrapper.registerModule('tia', new MensagensModule());
modulesWrapper.registerModule('patches', new PatchNotes());
modulesWrapper.registerModule('admin', new Admin());
modulesWrapper.registerModule('offend', new Offend());
modulesWrapper.registerModule('bored', new Bored());
modulesWrapper.registerModule('reset', new Reset());
modulesWrapper.registerModule('ban', new Ban());
modulesWrapper.registerModule('reveal', new Reveal());
modulesWrapper.registerModule('delete', new Delete());

export default modulesWrapper;
